# Generated by Django 4.1 on 2022-09-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresas', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=45)),
                ('sector_produc', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_app',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_contable',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('empleado_empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.empresas')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.empleado')),
                ('empleado_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.rol')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.empresas'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.rol'),
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('contabilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('empresas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.empresas')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.reporte_contable')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeloRelacionalBaseDeDatos.rol')),
            ],
        ),
    ]
